### ISSUE TITLE
Content disposition solved?

### ISSUE THREAD

**Issue by jheijmans** [ashishprajapati/activestorage-dropbox#11]
Using your gem (which works great), I bumped into the issue to get the original filename when downloading from Dropbox. It seems you yourself asked the same question on the Dropbox forum: https://www.dropboxforum.com/t5/Discuss-Dropbox-Developer-API/Content-Disposition-in-dropbox/td-p/340864

From the answer it seems Dropbox doesn't support this very well, but also that you seem to have some kind of way around it. Is that indeed the case, and if so, could you put that in the documentation?

**Comment by ashishprajapati** [comment]
@jheijmans, Yes, it's the known issue and you got the right Dropbox Support link where I was discussing around a year ago with Dropbox Team to add the support of passing the  **Content-disposition Headers**.

Dropbox doesn't provide support to set the **Content-disposition headers** dynamically. I kept convincing Dropbox Support to add this feature in dropbox so it will fix this issue. The ticket is still open but I am not sure if they are going to do any actions. They just need to provide the ability to pass the custom *Content-disposition headers** for the download request of the file.

If Dropbox will fix this issue then it will work smoothly like AWS S3, GCS and AZURE storage, etc those provide the support of passing **Content-disposition headers** dynamically while sending the download request for the file at storage server.

Yes, there is a workaround to fix it but frankly speaking, we were looking for the standard solution so we never made any temporary fixes. 

**Quick Fix:** I can't share in detail here at the moment but as I can observe if we will store the file with the original name at Dropbox then it will the best solution for the time being. There, we need to make some modifications within the `dropbox_service.rb` service file.

*I will check it this weekend and will try to find time to add a temporary fix for it. And I will release a new version of the gem.*

Later, we will do a standard fix when we will have the issue solved by Dropbox itself. 

I appreciate your feedback 👍 

Thanks,
Ashish Prajapati
