### ISSUE TITLE
Wraps the Dropbox Storage Service as an Active Storage service.

### ISSUE THREAD

**Issue by kinmt1234** [ashishprajapati/activestorage-dropbox#4]
Hi Ashish, First of all. Awesome Gem, thanks for sharing this. I have an issue on how to "wraps the dropbox storage service as an active storage service". I have created 'dropbox_service.rb' file inside `lib/active_storage/service` but i am getting `/Users/Desktop/project/lib/active_storage/service/dropbox_service.rb:15: syntax error, unexpected keyword_rescue, expecting keyword_end rescue DropboxApi::Errors::UploadError ^`

**Comment by ashishprajapati** [comment]
Hello @kinmt1234 

Thanks for your feedback ! 

I have few questions:
1. What was the requirement of creating your own `dropbox_service.rb` ? Are you trying to overriding something ? :) 
2. It's looking like there is some syntax error in your file that you created. Can you please cross check the syntax error ?

@kinmt1234 Have you followed the steps mentioned with in the README file
https://github.com/ashishprajapati/activestorage-dropbox/blob/master/README.md

Thanks,
Ashish P.

**Comment by kinmt1234** [comment]
Hi @ashishprajapati, thanks for your response. Nah, I am not trying to override anything. I have installed your gem and set up `storage.yml` how you explained in the `Readme` and added `config.active_storage.service = :dropbox` to `config/environments/development.rb:` but I was getting `Unable to autoload constant ActiveStorage::Blob::Analyzable, expected /Users/xxxx/.rvm/gems/ruby-2.2.6/gems/activestorage-5.2.2/app/models/active_storage/blob/analyzable.rb to define it`. so thought I need to create the own `dropbox_service.rb` to use your gem. Sorry I am very new to this! so am bit confused

**Comment by ashishprajapati** [comment]
Hello @kinmt1234 

Do you have migrations in place ? You need to run this below mentioned command to run the required migrations for the active storage support.

```
rails active_storage:install

```

**Comment by kinmt1234** [comment]
Hi @ashishprajapati, I removed `dropbox_servicate.rb` that I have created myself and run those command 

    rails active_storage:install
    bundle exec rake db:migrate

so what I did was to use your gem 

    #Gemfile
    gem 'activestorage-dropbox'


    #storage.yml
    dropbox:
    service: Dropbox
    access_token: <%= ENV['DROPBOX_ACCESS_TOKEN']%>


    #development.rb
    config.active_storage.service = :dropbox

and the error I am getting was

     /Users/xxxx/.rvm/gems/ruby-2.2.6/gems/activestorage-dropbox- 
    1.0.0/lib/active_storage/service/dropbox_service.rb:16: syntax error, unexpected keyword_rescue, 
    expecting keyword_end rescue DropboxApi::Errors::UploadError ^ 
    /Users/xxxx/.rvm/gems/ruby-2.2.6/gems/activestorage-dropbox- 
    1.0.0/lib/active_storage/service/dropbox_service.rb:29: syntax error

and it's very weird but when I refresh the page, it gives me this error 

     Unable to autoload constant ActiveStorage::Blob::Analyzable, expected 
    /Users/xxxx/.rvm/gems/ruby-2.2.6/gems/activestorage- 
    5.2.2/app/models/active_storage/blob/analyzable.rb to define it

I have used active storage to upload files to a remote cloud but want to change to `dropbox` and found your gem..so active storage should be set up in my app... Is there anything I need to do to use your gem other than what I did?

**Comment by ashishprajapati** [comment]
Nope, that's all you supposed to do. You have proper configurations in place.

```
#Gemfile
gem 'activestorage-dropbox'


#storage.yml
dropbox:
  service: Dropbox
  access_token: ""


#development.rb
config.active_storage.service = :dropbox
```

What's your Ruby & Rails versions ?

**Comment by kinmt1234** [comment]
It's Rails 5.2.2 and ruby 2.2.6.

**Comment by ashishprajapati** [comment]
Oh, you are using ruby 2.2.6 so it's not supporting this feature. Lesser then the ruby 2.5.0 version throws an error when we try to use rescue/else/ensure inside do/end blocks.

Ruby 2.5.0 and greater versions supports rescue/else/ensure inside do/end blocks.

https://blog.bigbinary.com/2017/10/24/ruby-2.5-allows-rescue-inside-do-end-blocks.html

# Newest Way ( Greater then 2.5 )
```
   def upload(key, io, checksum: nil, content_type: nil, disposition: nil, filename: nil)
      instrument :upload, key: key, checksum: checksum do
        client.upload_by_chunks "/"+key, io
      rescue DropboxApi::Errors::UploadError
        raise ActiveStorage::IntegrityError
      end
    end
```

# Older Way ( Lesser then 2.5 ) - Using begin with rescue
```
   def upload(key, io, checksum: nil, content_type: nil, disposition: nil, filename: nil)
      instrument :upload, key: key, checksum: checksum do
         begin
           client.upload_by_chunks "/"+key, io
         rescue DropboxApi::Errors::UploadError
           raise ActiveStorage::IntegrityError
         end
      end
    end
```

https://github.com/ashishprajapati/activestorage-dropbox/blob/master/lib/active_storage/service/dropbox_service.rb#L14

**Comment by kinmt1234** [comment]
Ah! that makes sense, that's why it keeps throwing a syntax error. Does that mean, I need to create a custom file with `begin rescue end`?

**Comment by ashishprajapati** [comment]
That's very true !!

Let me try that for you and you can put that file `dropbox_service.rb` with in your lib folder as you did initially :)

**Comment by kinmt1234** [comment]
Haha, legend @ashishprajapati ! Huge thanks

**Comment by ashishprajapati** [comment]
@kinmt1234 

Please create one file as dropbox_service.rb and put it with in the lib folder. Don't forget to require it with in the initializers.

```ruby
# frozen_string_literal: true

require "dropbox_api"

module ActiveStorage
  # Wraps the Dropbox Storage as an Active Storage service. See ActiveStorage::Service for the generic API
  # documentation that applies to all services.
  class Service::DropboxService < Service
    def initialize(**config)
      @config = config
    end

    def upload(key, io, checksum: nil, content_type: nil, disposition: nil, filename: nil)
      instrument :upload, key: key, checksum: checksum do
        begin
          client.upload_by_chunks "/"+key, io
        rescue DropboxApi::Errors::UploadError
          raise ActiveStorage::IntegrityError
        end
      end
    end

    def download(key, &block)
      if block_given?
        instrument :streaming_download, key: key do
          stream(key, &block)
        end
      else
        instrument :download, key: key do 
          begin
              download_for(key)
          rescue DropboxApi::Errors::NotFoundError
              raise ActiveStorage::FileNotFoundError
          end
        end
      end
    end

    def delete(key)
      instrument :delete, key: key do
        begin    
          client.delete("/"+key)
        rescue DropboxApi::Errors::NotFoundError
          # Ignore files already deleted
        end
      end
    end

    def delete_prefixed(prefix)
      instrument :delete_prefixed, prefix: prefix do
        begin
          client.delete("/"+prefix[0..-2])
        rescue DropboxApi::Errors::NotFoundError
          # Ignore files already deleted
        end
      end
    end

    def exist?(key)
      instrument :exist, key: key do |payload|
        begin
          answer = client.get_metadata("/"+key).present?
        rescue DropboxApi::Errors::NotFoundError
          answer = false
        end
        payload[:exist] = answer
        answer
      end
    end

    def url(key, expires_in:, filename:, disposition:, content_type:)
      instrument :url, key: key do |payload|
        generated_url = file_for(key).link 
        payload[:url] = generated_url
        generated_url
      end
    end

    private

      attr_reader :config

      def file_for(key)
        client.get_temporary_link("/"+key)
      end

      def download_for(key)
        client.download("/"+key) do |chunk|
          return chunk.force_encoding(Encoding::BINARY)
        end
      end

      # Reads the file for the given key in chunks, yielding each to the block.
      def stream(key)
        begin
          file = client.download("/"+key) do |chunk|
            yield chunk
          end
        rescue DropboxApi::Errors::NotFoundError
          raise ActiveStorage::FileNotFoundError
        end
      end

      def client
        @client ||= DropboxApi::Client.new(config.fetch(:access_token))
      end
  end
end
```

**Comment by kinmt1234** [comment]
@ashishprajapati, Sweet just tested now and found files are on Dropbox, works like a charm!! Cheers for your help. If you don't mind is there any way I can customize the file names uploaded on Dropbox?

**Comment by ashishprajapati** [comment]
@kinmt1234,
This is by design, from ActiveStorage Rails. The file is stored by it's key and without extension at any cloud storage.

But, you have always the filename at your local database and you can find using  i.e
```
@post.image.filename 
@post.image.content_type
```

[ If you still want to have filenames there at cloud storage then you can do that as well but you need to make some manipulations with in core codebase of activestorage-dropbox library ]

Have a nice day !

Thanks,
Ashish P.
